// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/admin/update-status-user": {
            "put": {
                "description": "สำหรับจัดการอนุมัติผู้ใช้ pending approved rejected",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Update User Status",
                "parameters": [
                    {
                        "description": "Request Update User Status",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RequestUpdateUserStatus"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/confirm-reset": {
            "post": {
                "description": "ใช้สำหรับยืนยันการรีเซ็ตรหัสผ่านของผู้ใช้ token จะหมดอายุภายใน 15 นาที",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Confirm reset password",
                "parameters": [
                    {
                        "description": "Confirm reset password payload",
                        "name": "confirm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RequestConfirmResetPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError400ResponseSwagger"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError401ResponseSwagger"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError500ResponseSwagger"
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "description": "ใช้สำหรับเข้าสู่ระบบผู้ใช้",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "User login payload",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RequestLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError400ResponseSwagger"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError500ResponseSwagger"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "description": "ใช้สำหรับออกจากระบบผู้ใช้",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError500ResponseSwagger"
                        }
                    }
                }
            }
        },
        "/v1/auth/reset": {
            "post": {
                "description": "ใช้สำหรับรีเซ็ตรหัสผ่านของผู้ใช้",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Reset user password",
                "parameters": [
                    {
                        "description": "Reset password payload",
                        "name": "reset",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RequestResetPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError400ResponseSwagger"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError500ResponseSwagger"
                        }
                    }
                }
            }
        },
        "/v1/auth/sessions": {
            "get": {
                "description": "ใช้สำหรับดึงข้อมูลคุกกี้ auth token ของผู้ใช้",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get user sessions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError401ResponseSwagger"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError500ResponseSwagger"
                        }
                    }
                }
            }
        },
        "/v1/dropdown/department": {
            "get": {
                "description": "ใช้สำหรับดึงข้อมูลแผนกทั้งหมด",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dropdown"
                ],
                "summary": "Get all departments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ResponseGetDepartments"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    }
                }
            }
        },
        "/v1/dropdown/district/{id}": {
            "get": {
                "description": "ใช้สำหรับดึงข้อมูลอำเภอทั้งหมดตามรหัสจังหวัด",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dropdown"
                ],
                "summary": "Get all districts by province ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Province ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ResponseGetDistricts"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    }
                }
            }
        },
        "/v1/dropdown/position": {
            "get": {
                "description": "ใช้สำหรับดึงข้อมูลตำแหน่งงานทั้งหมด",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dropdown"
                ],
                "summary": "Get all positions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ResponseGetPositions"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    }
                }
            }
        },
        "/v1/dropdown/province": {
            "get": {
                "description": "ใช้สำหรับดึงข้อมูลจังหวัดทั้งหมด",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dropdown"
                ],
                "summary": "Get all provinces",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ResponseGetProvinces"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    }
                }
            }
        },
        "/v1/dropdown/subdistrict/{id}": {
            "get": {
                "description": "ใช้สำหรับดึงข้อมูลตำบลทั้งหมดตามรหัสอำเภอ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dropdown"
                ],
                "summary": "Get all sub-districts by district ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "District ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ResponseGetSubDistricts"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    }
                }
            }
        },
        "/v1/user": {
            "get": {
                "description": "ใช้สำหรับดึงรายการผู้ใช้งานแบบแบ่งหน้า",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get all users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search first_name_th last_name_th first_name_en last_name_en",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user status (e.g., pending, approved, rejected)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to sort by",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc|desc)",
                        "name": "sortOrder",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseSuccessPaginationResponseSwagger"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError400ResponseSwagger"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError500ResponseSwagger"
                        }
                    }
                }
            },
            "post": {
                "description": "ใช้สำหรับสร้างผู้ใช้ใหม่ โดยจะไม่สามารถสร้างผู้ใช้ที่มีบัตรประชาชนซ้ำได้",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "อีเมล",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "รหัสผ่าน",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "คำนำหน้าชื่อ (TH)",
                        "name": "title_th",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "คำนำหน้าชื่อ (EN)",
                        "name": "title_en",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ชื่อ (TH)",
                        "name": "first_name_th",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "นามสกุล (TH)",
                        "name": "last_name_th",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ชื่อ (EN)",
                        "name": "first_name_en",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "นามสกุล (EN)",
                        "name": "last_name_en",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "เลขบัตรประชาชน (13 หลัก)",
                        "name": "id_card",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "ไฟล์รูปโปรไฟล์",
                        "name": "avatar",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "เบอร์โทร",
                        "name": "phone",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "รหัสพนักงาน",
                        "name": "employee_code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "เพศ",
                        "name": "gender",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "วันเกิด (YYYY-MM-DD)",
                        "name": "birth_date",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "วันที่เริ่มงาน (YYYY-MM-DD)",
                        "name": "hire_date",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ตำแหน่งงาน",
                        "name": "position_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "แผนก",
                        "name": "department_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ประเภทพนักงาน",
                        "name": "employment_type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ที่อยู่บรรทัดที่ 1",
                        "name": "address_line1",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ที่อยู่บรรทัดที่ 2",
                        "name": "address_line2",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ตำบล/แขวง",
                        "name": "subdistrict",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "อำเภอ/เขต",
                        "name": "district",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "จังหวัด",
                        "name": "province",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "รหัสไปรษณีย์",
                        "name": "postal_code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ประเทศ",
                        "name": "country",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ชื่อธนาคาร",
                        "name": "bank_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "เลขบัญชี",
                        "name": "account_no",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ชื่อบัญชี",
                        "name": "account_name",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseSuccess201ResponseSwagger"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError400ResponseSwagger"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError500ResponseSwagger"
                        }
                    }
                }
            }
        },
        "/v1/user/documents": {
            "put": {
                "description": "ใช้สำหรับอัปเดตเอกสารของผู้ใช้",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update user documents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Document type (avatars = รูปโปรไฟล์ , idcards = หลักฐานสำเนาบัตรประชาชน, graduation = หลักฐานการจบการศึกษา, transcript = หลักฐานการศึกษา, resume = หลักฐานการสมัครงาน, health = หลักฐานการตรวจสุขภาพ, military = หลักฐานการผ่านการเกณฑ์ทหาร, criminal = หลักฐานการตรวจประวัติอาชญากรรม, other = โฟลเดอร์อัปโหลดทั่วไป)",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Document file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError400ResponseSwagger"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError500ResponseSwagger"
                        }
                    }
                }
            }
        },
        "/v1/user/{id}": {
            "get": {
                "description": "ใช้สำหรับดึงข้อมูลผู้ใช้ตาม ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError400ResponseSwagger"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError500ResponseSwagger"
                        }
                    }
                }
            },
            "put": {
                "description": "ใช้สำหรับอัปเดตข้อมูลผู้ใช้ตาม ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User update payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RequestUpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError400ResponseSwagger"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError500ResponseSwagger"
                        }
                    }
                }
            },
            "delete": {
                "description": "ใช้สำหรับลบผู้ใช้ตาม ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Delete user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError400ResponseSwagger"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseError500ResponseSwagger"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Address": {
            "type": "object",
            "properties": {
                "address_line1": {
                    "description": "ที่อยู่บรรทัด 1",
                    "type": "string"
                },
                "address_line2": {
                    "description": "ที่อยู่บรรทัด 2",
                    "type": "string"
                },
                "country": {
                    "description": "ประเทศ",
                    "type": "string"
                },
                "district": {
                    "description": "อำเภอ",
                    "type": "string"
                },
                "postal_code": {
                    "description": "รหัสไปรษณีย์",
                    "type": "string"
                },
                "province": {
                    "description": "จังหวัด",
                    "type": "string"
                },
                "subdistrict": {
                    "description": "ตำบล",
                    "type": "string"
                }
            }
        },
        "dto.BankInfo": {
            "type": "object",
            "properties": {
                "account_name": {
                    "description": "ชื่อบัญชี",
                    "type": "string"
                },
                "account_no": {
                    "description": "เลขที่บัญชี",
                    "type": "string"
                },
                "bank_name": {
                    "description": "ชื่อธนาคาร",
                    "type": "string"
                }
            }
        },
        "dto.BaseError400ResponseSwagger": {
            "type": "object",
            "properties": {
                "data": {},
                "message_en": {
                    "type": "string",
                    "example": "Invalid request"
                },
                "message_th": {
                    "type": "string",
                    "example": "ข้อมูลไม่ถูกต้อง กรุณาตรวจสอบ"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                },
                "status_code": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "dto.BaseError401ResponseSwagger": {
            "type": "object",
            "properties": {
                "data": {},
                "message_en": {
                    "type": "string",
                    "example": "Unauthorized"
                },
                "message_th": {
                    "type": "string",
                    "example": "การเข้าถึงถูกปฏิเสธ"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                },
                "status_code": {
                    "type": "integer",
                    "example": 401
                }
            }
        },
        "dto.BaseError500ResponseSwagger": {
            "type": "object",
            "properties": {
                "data": {},
                "message_en": {
                    "type": "string",
                    "example": "Internal server error"
                },
                "message_th": {
                    "type": "string",
                    "example": "เกิดข้อผิดพลาดในระบบ"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                },
                "status_code": {
                    "type": "integer",
                    "example": 500
                }
            }
        },
        "dto.BaseResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message_en": {
                    "type": "string",
                    "example": "Success"
                },
                "message_th": {
                    "type": "string",
                    "example": "สำเร็จ"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "status_code": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "dto.BaseSuccess201ResponseSwagger": {
            "type": "object",
            "properties": {
                "data": {},
                "message_en": {
                    "type": "string",
                    "example": "User created successfully"
                },
                "message_th": {
                    "type": "string",
                    "example": "สร้างผู้ใช้สำเร็จ"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "status_code": {
                    "type": "integer",
                    "example": 201
                }
            }
        },
        "dto.BaseSuccessPaginationResponseSwagger": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.Pagination"
                },
                "message_en": {
                    "type": "string",
                    "example": "Success"
                },
                "message_th": {
                    "type": "string",
                    "example": "สำเร็จ"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "status_code": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "dto.Document": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "วันที่สร้างเอกสาร",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "วันที่ลบเอกสาร (soft delete)",
                    "type": "string"
                },
                "file_url": {
                    "description": "ลิงก์ไฟล์เอกสาร",
                    "type": "string"
                },
                "name": {
                    "description": "ชื่อเอกสาร",
                    "type": "string"
                },
                "type": {
                    "description": "ประเภทเอกสาร เช่น \"id_card\", \"degree\"",
                    "type": "string"
                },
                "uploaded_at": {
                    "description": "วันที่อัปโหลดเอกสาร",
                    "type": "string"
                }
            }
        },
        "dto.EmploymentHistory": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "description": "soft delete",
                    "type": "string"
                },
                "department_id": {
                    "description": "แผนกในช่วงเวลานั้น",
                    "type": "string"
                },
                "employment_type": {
                    "description": "ประเภทการจ้าง (เช่น full-time, intern)",
                    "type": "string"
                },
                "from_date": {
                    "description": "วันที่เริ่มต้น",
                    "type": "string"
                },
                "note": {
                    "description": "หมายเหตุ (ถ้ามี)",
                    "type": "string"
                },
                "position_id": {
                    "description": "ตำแหน่งในช่วงเวลานั้น",
                    "type": "string"
                },
                "to_date": {
                    "description": "วันที่สิ้นสุด (nullable ถ้ายังทำอยู่)",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "description": "รหัสผู้ใช้ที่เกี่ยวข้อง",
                    "type": "string"
                }
            }
        },
        "dto.Pagination": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ResponseGetUserAll"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "type": "integer",
                    "example": 10
                },
                "total_count": {
                    "type": "integer",
                    "example": 100
                },
                "total_pages": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "dto.RequestConfirmResetPassword": {
            "type": "object",
            "required": [
                "new_password",
                "token"
            ],
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.RequestLogin": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "อีเมลของผู้ใช้",
                    "type": "string"
                },
                "password": {
                    "description": "รหัสผ่าน",
                    "type": "string"
                }
            }
        },
        "dto.RequestResetPassword": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "อีเมลของผู้ใช้",
                    "type": "string",
                    "example": "example@mail.com"
                },
                "redirect_url": {
                    "description": "URL ที่จะเปลี่ยนเส้นทางหลังจากรีเซ็ตรหัสผ่าน",
                    "type": "string",
                    "example": "https://erp-demo-frontend.onrender.com"
                }
            }
        },
        "dto.RequestUpdateUser": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "ที่อยู่ของพนักงาน",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Address"
                        }
                    ]
                },
                "avatar": {
                    "description": "ลิงก์หรือที่อยู่รูปประจำตัวผู้ใช้",
                    "type": "string"
                },
                "bank_info": {
                    "description": "ข้อมูลบัญชีธนาคารของพนักงาน",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.BankInfo"
                        }
                    ]
                },
                "birth_date": {
                    "description": "วันเดือนปีเกิดของพนักงาน (รูปแบบ string)",
                    "type": "string"
                },
                "department_id": {
                    "description": "รหัสแผนก (FK ไปยัง Departments)",
                    "type": "string"
                },
                "documents": {
                    "description": "รายการเอกสารที่เกี่ยวข้องกับพนักงาน",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Document"
                    }
                },
                "email": {
                    "description": "อีเมลของผู้ใช้",
                    "type": "string"
                },
                "employee_code": {
                    "description": "รหัสพนักงาน (อาจใช้สำหรับอ้างอิงภายใน)",
                    "type": "string"
                },
                "employment_history": {
                    "description": "ประวัติการจ้างงาน (อาจมีหลายรายการ)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.EmploymentHistory"
                    }
                },
                "employment_type": {
                    "description": "ประเภทการจ้างงาน (เช่น full-time, part-time)",
                    "type": "string"
                },
                "first_name_en": {
                    "description": "ชื่อจริงของพนักงาน (ภาษาอังกฤษ)",
                    "type": "string"
                },
                "first_name_th": {
                    "description": "ชื่อจริงของพนักงาน",
                    "type": "string"
                },
                "gender": {
                    "description": "เพศของพนักงาน",
                    "type": "string"
                },
                "hire_date": {
                    "description": "วันที่เริ่มงาน",
                    "type": "string"
                },
                "id_card": {
                    "description": "หมายเลขบัตรประชาชน (อาจเข้ารหัสก่อนจัดเก็บ)",
                    "type": "string"
                },
                "last_name_en": {
                    "description": "นามสกุลของพนักงาน (ภาษาอังกฤษ)",
                    "type": "string"
                },
                "last_name_th": {
                    "description": "นามสกุลของพนักงาน",
                    "type": "string"
                },
                "password": {
                    "description": "รหัสผ่าน (อาจไม่ต้องการอัปเดต)",
                    "type": "string"
                },
                "phone": {
                    "description": "เบอร์โทรศัพท์ของพนักงาน",
                    "type": "string"
                },
                "position_id": {
                    "description": "รหัสตำแหน่งงาน (FK ไปยัง Positions)",
                    "type": "string"
                },
                "title_en": {
                    "description": "คำนำหน้าชื่อ (ภาษาอังกฤษ)",
                    "type": "string"
                },
                "title_th": {
                    "description": "คำนำหน้าชื่อ (ภาษาไทย)",
                    "type": "string"
                }
            }
        },
        "dto.RequestUpdateUserStatus": {
            "type": "object",
            "required": [
                "status",
                "user_id"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "enum": [
                        "pending",
                        "approved",
                        "rejected",
                        "cancelled"
                    ],
                    "example": "approved"
                },
                "user_id": {
                    "type": "string",
                    "example": "50f7a957-8c2c-4a76-88ed-7c247471f28f"
                }
            }
        },
        "dto.ResponseGetDepartments": {
            "type": "object",
            "properties": {
                "department_id": {
                    "description": "รหัสแผนก (ไม่ซ้ำกัน)",
                    "type": "string"
                },
                "department_name": {
                    "description": "ชื่อแผนก",
                    "type": "string"
                }
            }
        },
        "dto.ResponseGetDistricts": {
            "type": "object",
            "properties": {
                "district_id": {
                    "description": "รหัสอำเภอ (",
                    "type": "string"
                },
                "district_name": {
                    "description": "ชื่ออำเภอ",
                    "type": "string"
                }
            }
        },
        "dto.ResponseGetPositions": {
            "type": "object",
            "properties": {
                "position_id": {
                    "description": "รหัสตำแหน่งงาน (ไม่ซ้ำกัน)",
                    "type": "string"
                },
                "position_name": {
                    "description": "ชื่อตำแหน่งงาน",
                    "type": "string"
                }
            }
        },
        "dto.ResponseGetProvinces": {
            "type": "object",
            "properties": {
                "province_id": {
                    "description": "รหัสจังหวัด (ไม่ซ้ำกัน)",
                    "type": "string"
                },
                "province_name": {
                    "description": "ชื่อจังหวัด",
                    "type": "string"
                }
            }
        },
        "dto.ResponseGetSubDistricts": {
            "type": "object",
            "properties": {
                "sub_district_id": {
                    "description": "รหัสตำบล (ไม่ซ้ำกัน)",
                    "type": "string"
                },
                "sub_district_name": {
                    "description": "ชื่อตำบล",
                    "type": "string"
                },
                "zip_code": {
                    "description": "รหัสไปรษณีย์",
                    "type": "string"
                }
            }
        },
        "dto.ResponseGetUserAll": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "ลิงก์หรือที่อยู่รูปประจำตัวผู้ใช้",
                    "type": "string",
                    "example": "https://example.com/avatar.jpg"
                },
                "created_at": {
                    "description": "วันที่สร้างข้อมูลนี้",
                    "type": "string",
                    "example": "2025-07-11T08:25:08.526Z"
                },
                "deleted_at": {
                    "description": "วันที่ลบข้อมูล (soft delete)",
                    "type": "string",
                    "example": "null"
                },
                "department": {
                    "description": "รหัสแผนก (FK ไปยัง Departments)",
                    "type": "string",
                    "example": "DEP001"
                },
                "email": {
                    "description": "อีเมลของผู้ใช้",
                    "type": "string",
                    "example": "จันทรสกุล"
                },
                "first_name_en": {
                    "description": "ชื่อจริงของพนักงาน (ภาษาอังกฤษ)",
                    "type": "string",
                    "example": "Kittiya"
                },
                "first_name_th": {
                    "description": "ชื่อจริงของพนักงาน",
                    "type": "string",
                    "example": "กิตติยา"
                },
                "kpi_score": {
                    "description": "คะแนน KPI ของพนักงาน",
                    "type": "string",
                    "example": "85"
                },
                "last_name_en": {
                    "description": "นามสกุลของพนักงาน (ภาษาอังกฤษ)",
                    "type": "string",
                    "example": "Chanthasakul"
                },
                "last_name_th": {
                    "description": "นามสกุลของพนักงาน",
                    "type": "string",
                    "example": "จันทรสกุล"
                },
                "phone": {
                    "description": "เบอร์โทรศัพท์ของพนักงาน",
                    "type": "string",
                    "example": "094-222-7788"
                },
                "position": {
                    "description": "รหัสตำแหน่งงาน (FK ไปยัง Positions)",
                    "type": "string",
                    "example": "POS126"
                },
                "status": {
                    "description": "สถานะของผู้ใช้ (เช่น approved , pending, rejected)",
                    "type": "string",
                    "example": "approved"
                },
                "tasks_completed": {
                    "description": "จำนวนงานที่เสร็จสมบูรณ์",
                    "type": "string",
                    "example": "8"
                },
                "tasks_total": {
                    "description": "จำนวนงานทั้งหมดที่ได้รับมอบหมาย",
                    "type": "string",
                    "example": "10"
                },
                "title_en": {
                    "description": "คำนำหน้าชื่อ (ภาษาอังกฤษ)",
                    "type": "string",
                    "example": "Miss"
                },
                "title_th": {
                    "description": "คำนำหน้าชื่อ (ภาษาไทย)",
                    "type": "string",
                    "example": "นางสาว"
                },
                "updated_at": {
                    "description": "วันที่แก้ไขข้อมูลล่าสุด",
                    "type": "string",
                    "example": "2025-07-11T08:25:08.526Z"
                },
                "user_id": {
                    "description": "รหัสประจำตัวผู้ใช้ (ไม่ซ้ำกัน)",
                    "type": "string",
                    "example": "1d5855c2-7d14-4f8d-8b5d-ef20cb5cb3cf"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "erp-demo-9ux8.onrender.com",
	BasePath:         "/service/api",
	Schemes:          []string{},
	Title:            "ERP Demo API",
	Description:      "This is an ERP API demo.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
